### ISSUE TITLE
Should gulp-jekyll be blacklisted?

### ISSUE THREAD

**Issue by robwierzbowski** [gulpjs/plugins#101]
First let me say I'm a fan of Gulp's opinionated blacklisting.

Can you elaborate on the Jekyll blacklist? I want to use Jekyll as part of a Gulp stream, something like `jade -> jekyll -> (maybe other HTML transforms like useref ->) htmlmin`. Jekyll seems equivalent to Sass in that it's basically a complex Ruby-based preprocessor (of HTML instead of CSS). Using `spawn()`, I'll need to run jade, write to disk, trigger Jekyll, write to disk, and trigger htmlmin; a Grunt-like workflow that I'm trying to avoid.

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io

The blacklist isn't currently applied to the new plugin page. It is still used by --verify but that might change soon.
