### ISSUE TITLE
Blacklisted recommendation should come with docs

### ISSUE THREAD

**Issue by adregan** [gulpjs/plugins#106]
I like the idea of blacklisting plugins that duplicate existing node module functionality. However, the gulp plugins generally have very good documentation specifically _for_ gulp while the npm packages are more general.

It would be nice if there was at least a small example about integrating the npm package with gulp. Perhaps a default example:

```
use the xxxx module directly 

_link to module_ _example_
```

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io

The blacklist isn't currently applied to the new plugin page. It is still used by --verify but that might change soon.
