### ISSUE TITLE
Remove plugin gulp-freeze-resources from the blacklist

### ISSUE THREAD

**Issue by nyakto** [gulpjs/plugins#115]
**gulp-useref** and **gulp-freeze-resources** are different things: first one works with html, the second one with css.

The main goal of my plugin is to rename files referred from css (like images and fonts) using hash of file content and rewrite css accordingly. It allows to distribute such files with `Max-Age` for long living cache. If some files in project will be changed - they will simply change their names. It's a best cache practice simply because it avoid `If-Modified-Since` queries to server.

**Comment by Dejavs** [comment]
I think the blacklisting idea is the very, very bad thing here. It destroys very good plugins. Devs wake up and get out blacklist! Let us choose what we want to use. Sometimes you promote much worse plugins without good reason!

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io

The blacklist isn't currently applied to the new plugin page. It is still used by --verify but that might change soon.
