### ISSUE TITLE
Plugins page feedback

### ISSUE THREAD

**Issue by sindresorhus** [gulpjs/plugins#119]
Feedback on the new one:
- [x] search box should be centered
- [x] the title links should be more visible links, eg. underline on hover
- [x] less focus on the keywords. they steal focus and aren't that useful. make them smaller and more faded.
- [ ] sort by popularity
- [x] "No results" is flashed while loading. This should be hidden on load.

Additional improvements:
- [ ] show github stars
- [ ] show npm downloads

**Comment by nunoarruda** [comment]
It would be nice to have that "sort by popularity" feature to check what the community is using the most.

**Comment by stigok** [comment]
When I search for "load" I expect plugins that has "load" in the plugin name to be the first results.

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io
