### ISSUE TITLE
Keyboard scrolling doesn't work in Firefox

### ISSUE THREAD

**Issue by jakub-g** [gulpjs/plugins#121]
- Open http://gulpjs.com/plugins/ in Firefox 30
- click with the mouse anywhere on the page **except the white bar at the top** (`<nav>` in HTML)
- try scrolling the page using keyboard buttons: `pgup`, `pgdown`, `spacebar`, `arrow_down`, `arrow_up`

In Firefox that doesn't work for some reason (it's fine in Chrome). I haven't managed yet to find out why.

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io
