### ISSUE TITLE
Many gh-pages plugins

### ISSUE THREAD

**Issue by arthurvr** [gulpjs/plugins#142]
There are many duplicates living to the 'push to gh-pages branch' thing.

Try searching for 'gh-pages' on the plugins site, and there are already four doing the same thing. On the other hand everything these plugins do is available using gulp-subtree too.

Probably it's better to only have one of all those plugins. The best maintained one? the first one? Are you guys having experience which one works the best?

**Comment by arthurvr** [comment]
Done in 113a37f53edd598069e7aa231d6d1a89df47aaeb, a0c829c2fa6e9bc88d0deb56c80ff21ca4526507 and 71da4a6e8c67ec152acbc60ea55a521f1f8e8db1 so closing this.

**Comment by sindresorhus** [comment]
Awesome. Thanks @arthurvr :)
