### ISSUE TITLE
Trying to figure out why my plugin is not listed.

### ISSUE THREAD

**Issue by jisaacks** [gulpjs/plugins#156]
I published a [Gulp plugin](https://www.npmjs.com/package/gulp-mincer) to npm about a week ago. It has the keyword __gulpplugin__ yet does not show up at http://gulpjs.com/plugins/

Looking at the source code, it seems thats all I would need to do. It is not blacklisted either. Is there some reason it is now showing up or does it take a while?

**Comment by contra** [comment]
@jisaacks If you searched the issues you would see about 100 other issues for the same problem. The registry we run for the plugin search crashes sometimes and needs to be restarted. I don't have time to debug it, if you would like to send a PR to fix it please do so. I'll restart it again.
