### ISSUE TITLE
possible blackList error

### ISSUE THREAD

**Issue by kswin** [gulpjs/plugins#174]
Hello, 

I think line 141 in the blackList may be incorrect -> "gulp-add-src": "duplicate of gulp-inject". 

I tried to use gulp inject to add more sources down the pipeline, but it didn't work, and based on their description, the plugins seem to be solving different problems. gulp-inject seems to be a way to dynamically add js dependencies to the index page whereas gulp-add-src lets you expand on the gulp.src stream you started with.

**Comment by devel-pa** [comment]
+1

**Comment by robinj** [comment]
+1

**Comment by contra** [comment]
PR?
