### ISSUE TITLE
gulp-exec

### ISSUE THREAD

**Issue by stevemao** [gulpjs/plugins#177]
both `gulp-shell` and `gulp-run` look more actively maintained than `gulp-exec`. `gulp-shell` has more stars than `gulp-exec`

**Comment by sindresorhus** [comment]
https://github.com/gulpjs/plugins/pull/202

**Comment by dboune** [comment]
sun-zheng-an/gulp-shell#55

sun-zheng-an/gulp-shell@75e3b877

**Comment by stevemao** [comment]
@phated why is this closed?

**Comment by phated** [comment]
Because we aren't going to deprecate them.  Even though they've updated the readme to explain the anti-pattern.  We don't unblacklist because of stars or anything and gulp-exec is still maintained (I just reviewed)
