### ISSUE TITLE
daguike-gulp-rev-del

### ISSUE THREAD

**Issue by callumacrae** [gulpjs/plugins#178]
This is a fork of rev-del where some dude fixed a bug (I don't even know what the bug is), and then decided to not contribute it back to rev-del.

https://github.com/daguike/rev-del

Could it be blacklisted?

**Comment by contra** [comment]
Yeah and also encourage them to send the fix back

**Comment by callumacrae** [comment]
I left a comment. I don't know what bug they've even fixed, though.
