### ISSUE TITLE
Creating a new plugin which may be deemed as a duplicate of a no longer maintained plugin?

### ISSUE THREAD

**Issue by jh3y** [gulpjs/plugins#181]
I'm looking to create a gulp plugin that will create a templates file consisting of a user defined namespace of different files. Say a user picks `TMPL`.

```javascript
var TMPL = {
  'templates/template': '<html>...</html>'
};
```

This could either be blocks of HTML or a keyed object of `lodash` functions. With the latter, it would be best to provide interpolation options naturally.

This type of file is used similarly to angulars template cache and would be used in a concatenation of scripts for deployment.

If I am to create this plugin, I can foresee it being blacklisted as a duplicate of `gulp-jst-concat` although `gulp-jst-concat` doesn't offer the ability to use `lodash` options and I find its options to not be as intuitive as possible.

The other issue here is that `gulp-jst-concat` hasn't been touched in over a year nor has it's owner been active for over a year although people are posting issues. It would seem unfair to be blacklisted if I was to implement a newer version that was actively maintained by myself. I can see this being an issue with other plugins too.

@jh3y

**Comment by sindresorhus** [comment]
We want what's best for the gulp ecosystem. We're happy to blacklist the existing one if it's unmaintained and yours is better.

**Comment by jh3y** [comment]
Sweet. I'll get to work. Thanks @sindresorhus !
