### ISSUE TITLE
CORS...

### ISSUE THREAD

**Issue by BigBlueHat** [gulpjs/plugins#182]
Similar to #127 

Getting CORS errors in Firefox 36 and it's not loading in the latest Chrome...though no console errors that I could see.

Here's what Firefox says:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://registry.gulpjs.com/_search?fields=name,keywords,rating,description,author,modified,homepage,version&from=0&q=keywords:gulpplugin,gulpfriendly&size=20. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by Spy-Seth** [comment]
I have the same error. The search do not works.

**Comment by contra** [comment]
Honestly I think I might just shut down the search and redirect it to npm unless somebody else wants to maintain it

**Comment by sindresorhus** [comment]
@contra Any reason you can't just use http://npmsearch.com/query?fields=name,keywords,rating,description,author,modified,homepage,version,license&q=keywords:gulpplugin&size=15&sort=rating:desc&start=0 directly?

**Comment by contra** [comment]
@sindresorhus That didn't exist when we made this. I actually requested that and they said it was in progress, but never heard back from them. We can definitely switch over if somebody wants to send a PR

**Comment by Spy-Seth** [comment]
Here the PR https://github.com/gulpjs/plugins/pull/189
