### ISSUE TITLE
Plugin search on website doesn't work

### ISSUE THREAD

**Issue by ad-on-is** [gulpjs/plugins#188]
When I go to: http://gulpjs.com/plugins/ there is nothing there. Only the searchbar and the orange body background. Also if I start typing some text or hit enter, still nothing happens.

OS X Yosemite 10.10.3
Tried in Chrome, Firefox, Safari

**Comment by contra** [comment]
duplicate of #182 i dont have time to maintain it, im going to redirect it to npm this week and shut it down unless somebody else wants to take ownership
