### ISSUE TITLE
Why is gulp-node-inspector on the blacklist?

### ISSUE THREAD

**Issue by lirantal** [gulpjs/plugins#214]
Can anyone clarify why is this plugin on the blacklist?
Did anyone contact the maintainer to communicate anything?

```
"gulp-node-inspector": "not a gulp plugin, very bad patterns",
```

**Comment by phated** [comment]
Please read the gulp guidelines. There is no reason for this module to be a stream.  The gulpjs maintainers aren't able to reach out to every project that doesn't follow the guidelines.

**Comment by lirantal** [comment]
I wasn't expecting any special treatment was just raising this question.
How about providing alternatives for blacklisted modules? this will provide people with a clear update path rather than send them on a goose chase and further fragment the community between different plugins.

WDYT?

**Comment by phated** [comment]
Yep, we try to suggest alternatives. Here, the user can probably just use child_process spawn. Mind sending a PR? I'm away from keyboard currently.

**Comment by lirantal** [comment]
In this case, wouldn't you say that `gulp-nodemon` should also be blacklisted for the same reason? src: https://github.com/JacksonGariety/gulp-nodemon
