### ISSUE TITLE
[Review Request] a new gulp browserify plugin

### ISSUE THREAD

**Issue by kt3k** [gulpjs/plugins#216]
I'm trying creating a new gulp browserify plugin.

I've refered to these threads (https://github.com/gulpjs/plugins/issues/47 https://github.com/gulpjs/gulp/issues/369)

My understanding of the requirement is:

- If the plugin handles only one bundle, it doesn't fit the plugin paradigm because that is what browserify already does.
  - The plugin need to handle multiple bundles well.
- The plugin would probably work as a stream head. It replaces `gulp.src(...)`.

This is my attempt: https://github.com/kt3k/gulp-browserify2

My solution is basically similar to the multiple destination recipe which I committed last year: https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-multiple-destination.md

The implementation is just about 30 sloc for now. Can you review this and check if this fits the plugin concept? @contra @phated

I believe it's beneficial for gulp community to have officially acknowledged simple browserify plugin.

**Comment by phated** [comment]
@kt3k a couple of things:
* it should be named vinyl-browserify
* it should *not* have a `through` method but instead, `src` should be able to be used as a readable or through stream like vinyl-fs.  See: https://github.com/gulpjs/vinyl-fs#optionspassthrough
* it should support as many of the vinyl-fs options as possible
* is there a valid use case/implementation of `vinyl-browserify.dest()`?
* it should support back to node 0.10 like the rest of the ecosystem

**Comment by kt3k** [comment]
Thanks for the feedback! @phated

> it should be named vinyl-browserify
> it should be tagged as gulpfriendly, not a gulpplugin

Ah, this means this isn't a plugin in strict sense and better to make it `gulpfriendly`. OK, I see.

By the way, vinyl-browserify is already taken in npm registry. Can I name it anything like `browserify-vinyl` or `@kt3k/vinyl-browserify`(using [scoped package](https://docs.npmjs.com/getting-started/scoped-packages))? Is there any naming conventions/rules for `gulpfriendly` modules?

> it should not have a through method but instead, src should be able to be used as a readable or through stream like vinyl-fs. See: https://github.com/gulpjs/vinyl-fs#optionspassthrough
> it should support as many of the vinyl-fs options as possible
> it should support back to node 0.10 like the rest of the ecosystem

I'll try work on these points. Thanks.

> is there a valid use case/implementation of vinyl-browserify.dest()?

I don't think there's a use case of this (or even I don't quite imagine what happens with vinyl-browserify.dest().)

**Comment by kt3k** [comment]
- I changed the name to `browserify-vinyl` for the moment.
- removed `gulpplugin`, added `gulpfriendly`
- added support of node 0.10. (tests pass with node v0.10)
  - though I kept es6 (of node v4) in README because many people seem moving to node v4.
- added the 3rd param to `vinyl-browserify.src` and it's passed to `vinyl-fs.src`
- removed `vinyl-browserify.through`
- vinyl-browserify.src(paths, browserifyOpts, {passthrough: ture}) works as transform stream, adding entries from paths.
- vinyl-browserify.src(null, browserifyOpts, {passthrough: true}) works as well. It performs purely transform through the stream.

**Comment by phated** [comment]
@kt3k 

* It should be named `vinyl-browserify` - ask the author for the npm name or work together
* You shouldn't be depending on `vinyl-fs` but instead should be implementing features like it does and use the `glob-stream` library.
* Don't add a 3rd argument for vinyl options; Instead, intermingle the browserify options with the vinyl options or add a `browserify` property to the options.  I think intermingling and passing them through is the best option here because we do the same with vinyl-fs (passing options to glob-stream and glob, etc).
* I don't think you should support `null` in the first `src` argument, in vinyl-fs, we use `is-valid-glob` to check for valid globs; You should too.

**Comment by kt3k** [comment]
@phated

> It should be named vinyl-browserify - ask the author for the npm name or work together

I'll try.

> You shouldn't be depending on vinyl-fs but instead should be implementing features like it does and use the glob-stream library.

I dropped `vinyl-fs` from deps and added `glob-stream`, `vinyl`, `duplexify` etc.

> Don't add a 3rd argument for vinyl options; Instead, intermingle the browserify options with the vinyl options or add a browserify property to the options. I think intermingling and passing them through is the best option here because we do the same with vinyl-fs (passing options to glob-stream and glob, etc).

I mixed two sets of options. (First I thought it's a bit confusing because both have not so small number of options and they have some overlaps (I found at least one example `debug: true`), but after thinking, I agree that having two separate option sets feels a bit ugly.)

> I don't think you should support null in the first src argument, in vinyl-fs, we use is-valid-glob to check for valid globs; You should too.

In case of `passthrough: false` (this is default), I added `is-valid-glob` check to `paths`. In case of `passthrough: true`, I kept null support of paths because unlike the case of `vinyl-fs`, vinyl-browserify.src(null, {passthrough: true}) still have meaningful function (to transfrom incoming vinyls).

**Comment by kt3k** [comment]
Hello

I also added support of some options such as `buffer`, `sourcemaps` and `since`

The followings are supported and explicitly documented options for now.

- cwd - passed to glob-stream
- base - passed to glob-stream
- buffer - Implemented in this module
- sourcemaps - Implemented in this module
- since - Implemented in this module
- transform - passed to browserify
- debugGlobStream - passed to glob-stream (as `debug`)
- passthrough - Implemented in this module

The followings are options which `vinyl-fs` supports but I don't think it's reasonable to support in this module.

- stripBOM - keeping bom in files breaks the bundle.
- followSymlinks - `false` doesn't make much sense.
- read - `false` doesn't make much sense.

I also added CI settings, such as lint, circleci and codecov.

> vinyl-browserify

I asked the author for the name. I haven't received an answer for about a week. Now I'm afraid this proposal doesn't make much sense and think `vinyl-bundle` is a better choice because what browserify does is only bundling the scripts. (We can clarify how this uses browserify and the options are passed to it in README.md.) How do you think?

https://github.com/kt3k/vinyl-bundle
