### ISSUE TITLE
Remove gulp-jsbeautifier from blacklist

### ISSUE THREAD

**Issue by biasso** [gulpjs/plugins#217]
[gulp-jsbeautifier](https://www.npmjs.com/package/gulp-jsbeautifier) has been blacklisted as duplicate of [gulp-beautify](https://www.npmjs.com/package/gulp-beautify).

Both are wrappers for [js-beautify](https://www.npmjs.com/package/js-beautify) but gulp-jsbeautifier has more features then gulp-beautify.

gulp-beautify works only for javascripts while gulp-jsbeautifier also works for css and html (like js-beautify).

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io

The blacklist isn't currently applied to the new plugin page. It is still used by --verify but that might change soon.
