### ISSUE TITLE
Blacklist gulp-static-site

### ISSUE THREAD

**Issue by strugee** [gulpjs/plugins#228]
It seems to me that https://www.npmjs.com/package/gulp-static-site should be blacklisted for doing too much, but I'm not 100% sure. Happy to open a PR fixing this.

/cc @0x01 for politeness

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io

The blacklist isn't currently applied to the new plugin page. It is still used by --verify but that might change soon.
