### ISSUE TITLE
Add gulp-sass to blacklist or remove gulp-requirejs

### ISSUE THREAD

**Issue by Joelsz** [gulpjs/plugins#238]
The reason for "gulp-requirejs" being blacklisted, from blacklist.json:
`"gulp-requirejs": "use the require.js module directly",`

As I can understand the reason why it's being blacklisted is, that it is not just handling the current stream but is using other files (the file system) while executing it's processes (to include the required modules).

That said, gulp-sass should be handled the same way, since it is also importing files from the file system if there's a `@import` in the current stream (just like requirejs).

So to be consistent, please add gulp-sass to the blacklist or remove gulp-requirejs from the blacklist.

**Comment by contra** [comment]
Reviewing gulp-requirejs it looks like they've significantly changed the way it works and I believe we should remove it from the list. It now operates at the head of the stream and produces vinyl files like many other modules do.

IIRC (this was a long time ago) it used to break a bunch of conventions (sat in the middle of the stream, discarded inbound events, etc.) that got it on the list.

**Comment by Joelsz** [comment]
@contra that was fast. Thank you!
