### ISSUE TITLE
gulp-remove-code does not work with cshtml files

### ISSUE THREAD

**Issue by lidvarko** [gulpjs/plugins#239]
If the file extension is cshtml, then the gulp-remove-code does not recognise the `<!--removeIf(production)-->` comment within the HTML section. This works fine if I rename the file to html. Please add support for cshtml file format that may contain both html and c# code ( `<!--  -->` or `//` as comment)

**Comment by contra** [comment]
You should open a ticket on that repo then, this repo just tracks our plugin webpage - it has nothing to do with that module.
