### ISSUE TITLE
Un-blacklist gulp-connect

### ISSUE THREAD

**Issue by LandonSchropp** [gulpjs/plugins#240]
I'd like to request that `gulp-connect` be removed from the blacklist. Currently, the suggestion given is this:

> use the connect module directly

gulp-connect does quite a bit more than just starting a Connect server.

* It provides a simple, pre-configured server task function.
* It includes a `reload` function that can be chained at the end of a task to automatically reload the server.
* It sets up LiveReload so I don't have to.

Reimplementing all of that would be a pain in every project without using gulp-connect.

I tried to search for some example or documentation on how I would set up Gulp and Connect without gulp-connect, but I couldn't find any. Every reference I suggested using gulp-connect. I did find [this issue](https://github.com/gulpjs/plugins/issues/55), which suggested to read the documentation and use Connect as is. When I looked through the Connect documentation, the impression I got was I'd have to reimplement all of gulp-connect to get the same functionality. I don't see the benefit in that.

It seems to be that gulp-connect has a legitimate use case. If you have a suggestion of how I could approach this problem differently, I'd appreciate a reply with more detail.

Thanks!

**Comment by phated** [comment]
Modules shouldn't provide tasks. Gulp 4 has custom registries for that use case.

**Comment by LandonSchropp** [comment]
@phated Thanks for the quick reply. I'm not quite following the issue. I don't see anywhere in the gulp-connect codebase where it's providing a task. Am I missing something? Can you reopen this issue until there's a more definitive answer on how to solve this problem?

If you don't think I should use gulp-connect, do you have an alternative suggestion about how I could accomplish this without gulp-connect? Is there an example I could look at? Is there some kind of documentation?

**Comment by LandonSchropp** [comment]
@phated Could you please comment on this or reopen the issue? I don't feel like my original question was addressed.
