### ISSUE TITLE
Un-blacklist gulp-livereload

### ISSUE THREAD

**Issue by lorenzos** [gulpjs/plugins#242]
[gulp-livereload][2] is currently blacklisted with the reason *abandoned. use [gulp-refresh][1]*.  
I'm aware of #211, but at the time of writing:

1. gulp-refresh repository has been archived by the owner, it's now read-only; gulp-livereload is not.
2. gulp-refresh's last commit is about 3 years old; gulp-livereload's is 5 months.
3. gulp-refresh depends on a deprecated package (gulp-util, which triggers a warning during `npm install`); gulp-livereload does not.

The last reason is the one that personally made me switch back to gulp-livereload.

[1]: https://github.com/leo/gulp-refresh/
[2]: https://github.com/vohof/gulp-livereload

**Comment by phated** [comment]
@lorenzos I would probably agree based on your bullet points but gulp reload uses event-stream which was a security hazard, is unmaintained, and doesn't even do streams right. I don't want to recommend it with those issues.

**Comment by lorenzos** [comment]
@phated So does gulp-refresh, as I see [here](https://github.com/leo/gulp-refresh/blob/master/package.json#L34). Also, gulp-livereload [did something](https://github.com/vohof/gulp-livereload/pull/140) to address the issue, gulp-refresh did not.

**Comment by phated** [comment]
So I should blacklist both?  Sounds good.

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io

The blacklist isn't currently applied to the new plugin page. It is still used by --verify but that might change soon.
