### ISSUE TITLE
[blackList Database] Extract Blacklist to an own service

### ISSUE THREAD

**Issue by robinboehm** [gulpjs/plugins#60]
We should extract the "Gulp-BlackList" to a general BlackList repo.
So many blackList PR's and issues in this repo that aren't related to the actual plugin site. That sucks.
If we use a general repo, we could provide more blackLists or in an future-step a system/engine that allows to create a blackList database.

Task: Create and maintain a general blackList service 
Who wants to do that? I've no time to maintain this.

@Contra @sindresorhus

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io
