### ISSUE TITLE
Use nodechecker.com to figure out if a module has passing tests

### ISSUE THREAD

**Issue by contra** [gulpjs/plugins#76]
We can sort them a bit lower if the tests are failing or don't exist

Example: http://nodechecker.com/#info/gulp

We may want to host our own since the interval at which they scan may not be fast enough and we can filter out only gulpplugin/gulpfriendly modules

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io
