### ISSUE TITLE
Should plugins without source links be blacklisted or demoted?

### ISSUE THREAD

**Issue by robrich** [gulpjs/plugins#99]
Should lack of valid source link in package.json be grounds for blacklisting or for demoting in the list?  For example https://www.npmjs.org/package/fd-gulp-jsmin contains a source link to gitlab.alibaba-inc.com which doesn't exist.  The only way for me to understand how this plugin works is to download it and try it.  That seems less effective

**Comment by phated** [comment]
Closing this because the plugin page has been rewritten and integrated with our main website: https://github.com/gulpjs/gulpjs.github.io
